---
title: "Stats from Classifier Data"
author: Sebastian Holt
output: html_notebook
---

```{r libraries, echo=FALSE}

library(lme4) # need for running lmer
library(tidyverse)
library(coda)
require(languageR)
library(lmerTest) #need this for lmer p values!!
library(emmeans)
library(data.table)
library(ggplot2)
# install.packages('sjPlot')
library(sjPlot)


```


```{r get_data, echo=FALSE}
Rdf <- read_csv("datastructures/recogData.csv")
Rdf$block <- floor((Rdf$orig_game_trial_num - 1) / 8) + 1 # get block number from trial number of original game
Rdf <- Rdf[!is.na(Rdf$block),]

# remove the stuff that's not relevant for analysis
Rdf[2] <- NULL # gets rid of the column called "_id" that won't delete by name because of the underscore
Rdf$iterationName <- NULL
Rdf$assignmentID <- NULL
Rdf$hitID <- NULL
Rdf$turkSubmitTO <- NULL
Rdf$orig_stim_version <- NULL
Rdf$sketch_url <- NULL
Rdf$catch_trial <- NULL

# just rename everything for compactness's sake:
names(Rdf)[names(Rdf) == "recog_gameID"] <- "RgameID"
names(Rdf)[names(Rdf) == "orig_game_id"] <- "OgameID"
names(Rdf)[names(Rdf) == "rating_trial_num"] <- "Rtrial"
names(Rdf)[names(Rdf) == "orig_game_trial_num"] <- "Otrial"
names(Rdf)[names(Rdf) == "rate_condition"] <- "Rcond"
names(Rdf)[names(Rdf) == "orig_game_condition"] <- "Ocond"
names(Rdf)[names(Rdf) == "orig_sketch_animal"] <- "shape"
names(Rdf)[names(Rdf) == "orig_sketch_cardinality"] <- "cardinality"


```
### predict accuracy
```{r acc_2nd_submission}
# first look at all interactions:
# Ocond * Rcond * block * cardinality * shape    # BIC ??                     # didn't converge
# then the winner from original submission:
# Ocond * Rcond * block    # BIC ??                                           # didn't converge
# remove the interactions:
# Ocond + Rcond + block    # BIC 18152.68                                     #
# add back in the obvious interaction of conditions:
# Ocond * Rcond + block    # BIC 15139.2                                      # 
# maybe an effect of number too?:
# Ocond * Rcond + block + cardinality   # BIC ??                              # didn't converge
# or a number:Rcond interaction?:
# Ocond * Rcond + block + Rcond:cardinality   # BIC ??                        # didn't converge
# do we really need block?:
# Ocond * Rcond    # BIC 15352.44                                             # didn't converge

# https://stats.stackexchange.com/questions/228800/crossed-vs-nested-random-effects-how-do-they-differ-and-how-are-they-specified
# what if we have original game as a random effect?:
# Ocond * Rcond + block + (1  | workerID) + (1  | OgameID)   # BIC 15036.93   #
# add cardinality and shape as random effects?:
# + (1| workerID) + (1| OgameID) + (1|cardinality) + (1|shape) # BIC 15010.13 # winner?
# remove cardinality as random effect?:
# + (1| workerID) + (1| OgameID) + (1|shape)                  # BIC 15012.25  #
# remove shape as random effect?:
# + (1| workerID) + (1| OgameID) + (1|cardinality)            # BIC 15035.04  #
# keep all random effects and add in interaction with block:
# Ocond * Rcond * block                                       # BIC 14990.33  # didn't converge

correct <- glmer(data=Rdf, correct ~ 
                   Ocond * Rcond + block
                  + (1  | workerID) + (1  | OgameID) + (1|cardinality) + (1|shape),
                  family = 'binomial')
BIC(correct)
summary(correct)

```


### Look at reaction time
```{r RT}
RT <- lmer(data=Rdf,
                  RT ~ Ocond * Rcond + block + cardinality  + shape
                  + (1  | workerID))
BIC(RT)
summary(RT)
```