---
title: "Stats from Production Task"
author: Sebastian Holt
output: html_notebook
---

```{r libraries, echo=FALSE}

library(lme4) # need for running lmer
library(tidyverse)
library(coda)
require(languageR)
library(lmerTest) #need this for lmer p values!!
library(emmeans)
library(data.table)


```

```{r get_data, echo=FALSE}
# import the data that was output from internum_analysis.ipynb
# dat1 = read_csv("../results/csv/iterated_number_group_data_run1.csv")
# dat2 = read_csv("../results/csv/iterated_number_group_data_run2.csv")
# dat3 = read_csv("../results/csv/iterated_number_group_data_run3.csv")
# dat4 = read_csv("../results/csv/iterated_number_group_data_run4.csv")
# dat5 = read_csv("../results/csv/iterated_number_group_data_run5.csv")
dat6 = read_csv("../results/csv/iterated_number_group_data_run6.csv")
# dat = rbind(dat2, dat3, dat4, dat5, dat6)
# games = unique(dat$gameID)

dud_games = c(#"6769-3ee1e797-2c5b-4441-8d67-5ccd1c6b9a73",    #number
             "8369-76e6f73d-922a-4aca-b98a-8c96026aa48a",    #number
             "1372-60cdfd55-28bb-411c-b777-c51eaadee7a9",    #shape
             "2949-1e579088-8493-4c07-873c-7bd6d00685e3",    #shape
             "7197-6d1f3fda-040a-455c-aef0-279ba9aef053",    #shape
             "9237-4cc76e85-9955-4cef-b03c-5c68f46321ca",    #shape
             "1947-29382ba4-5747-456d-ba8b-276812fc1fb3")    #shape
bad_games <- dat6[ dat6$gameID %in% dud_games, ]
dat <- dat6[ ! dat6$gameID %in% dud_games, ]
dat$block <- floor((dat$trialNum - 1) / 8) + 1 # get block number from trial number

dat_num = filter(dat,Game_Condition == 'number')
dat_aml = filter(dat,Game_Condition == 'shape')

```


### several maximal models
```{r maximal_models}
# for each DV (total ink, number of strokes, and draw duration) store the lmer
lmer_ink <- lmer(data = dat,
                 meanPixelIntensity ~ cardinality * category * Game_Condition * block
                 + (1 + cardinality * category | gameID))

lmer_str <- lmer(data = dat,
                 numStrokes ~ cardinality * category * Game_Condition * block
                 + (1 + cardinality * category | gameID))

lmer_dur <- lmer(data = dat,
                 drawDuration ~ cardinality * category * Game_Condition * block
                 + (1 + cardinality * category | gameID))

glmer_ac <- glmer(data=dat,
                  outcome ~ cardinality * category * Game_Condition * block
                  + (1 + cardinality * category | gameID),
                  family = 'binomial')
```
### These appear to not converge. So let's simplify the models

``` {r annotated BIC comparisons}

# predicting meanPixelIntensity, using...
# Full model with cardinality in random effects:
# cardinality * category * Game_Condition * block + (1 + cardinality | gameID))    # BIC -9781.206
# Remove all the interaction terms:
# cardinality + category + Game_Condition + block + (1 + cardinality | gameID))    # BIC -10215.27  # winner?
# Remove block:
# cardinality + category + Game_Condition + (1 + cardinality | gameID))            # BIC -10214.78
# Remove game condition as well:
# cardinality + category + (1 + cardinality | gameID))                             # BIC -10184.58
# Reintroduce the interaction between number & shape?
# cardinality * category + (1 + cardinality | gameID))                             # BIC -10120.29
# Include interaction between cardinality and/or category and game condition:
# cardinality + category * Game_Condition + block + (1 + cardinality | gameID))    # BIC -10165.93
# cardinality + category + Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC -10203.72  # winner!
# cardinality + category * Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC -10154.39
ink_model <- lmer(data = dat, meanPixelIntensity ~ 
               cardinality + category + Game_Condition + block + (1 + cardinality | gameID))
summary(ink_model)

ink_no_car <- lmer(data = dat, meanPixelIntensity ~ 
               category + Game_Condition + block + (1 + cardinality | gameID))

anova(ink_model,test1)
# predicting numStrokes, using...
# Full model with cardinality in random effects:
# cardinality * category * Game_Condition * block + (1 + cardinality | gameID))    # BIC 9605.77
# Remove all interaction terms:
# cardinality + category + Game_Condition + block + (1 + cardinality | gameID))    # BIC 9587.28  # winner?
# Remove block:
# cardinality + category + Game_Condition + (1 + cardinality | gameID))            # BIC 9686.597
# Remove game condition as well:
# cardinality + category + (1 + cardinality | gameID))                             # BIC 9702.524
# Reintroduce the interaction between number & shape?
# cardinality * category + (1 + cardinality | gameID))                             # BIC 9735.728
# Reintroduce that interaction into the currently winning model:
# cardinality * category + Game_Condition + block + (1 + cardinality | gameID))    # BIC 9620.815
# Include interaction between cardinality and/or category and game condition:
# cardinality + category * Game_Condition + block + (1 + cardinality | gameID))    # BIC 9496.323 # didn't converge
# cardinality + category + Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC 9555.483
# cardinality + category * Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC 9464.525 # winner!
str_model <- lmer(data = dat, numStrokes ~
               cardinality + category * Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))

# how does the model fare when you take out each relevant predictor? This will tell us how much variability in animals is predictive of str, rather than a different esimate for each particular animal
str_no_cat <- lmer(data = dat, numStrokes ~
               cardinality * Game_Condition + block + (1 + cardinality | gameID))
str_no_car <- lmer(data = dat, numStrokes ~
               category * Game_Condition + block + (1 + cardinality | gameID))

anova(str_model,str_no_cat)
anova(str_model,str_no_car)
BIC(str_model)
summary(str_model)
# predicting drawDuration, using...
# Full model with cardinality in random effects:
# cardinality * category * Game_Condition * block + (1 + cardinality | gameID))    # BIC 10236.73
# Remove all interaction terms:
# cardinality + category + Game_Condition + block + (1 + cardinality | gameID))    # BIC 10162.24  # winner?
# Remove block:
# cardinality + category + Game_Condition + (1 + cardinality | gameID))            # BIC 10617.5
# Remove game condition as well:
# cardinality + category + (1 + cardinality | gameID))                             # BIC 10627.63
# Reintroduce the interaction between number & shape?
# cardinality * category + (1 + cardinality | gameID))                             # BIC 10658.04
# Reintroduce that interaction into the currently winning model:
# cardinality * category + Game_Condition + block + (1 + cardinality | gameID))    # BIC 10194.77
# Include interaction between cardinality and/or category and game condition:
# cardinality + category * Game_Condition + block + (1 + cardinality | gameID))    # BIC 10179.82
# cardinality + category + Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC 10125.5  # winner!
# cardinality + category * Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))    # BIC 10143.08
dur_model <- lmer(data = dat, drawDuration ~
               cardinality + category + Game_Condition + cardinality:Game_Condition + block + (1 + cardinality | gameID))
summary(dur_model)
# predicting outcome, using...
# Model with only intercept in random effects :
# cardinality * category * Game_Condition * block + (1 | gameID)            # BIC 1129.357  # doesn't converge
# Model with only intercept in random effects and no interactions:
# cardinality + category + Game_Condition + block + (1 | gameID)            # BIC 1003.702  # winner?
# Remove Game_Condition & block:
# cardinality + category + (1 | gameID)                                     # BIC 1024.696
# Reintroduce the interaction term between them:
# cardinality * category + (1 | gameID)                                     # BIC 1044.447  # also doesn't converge
# Remove the random effect entirely and add back in all fixed effects:
# cardinality + category + Game_Condition + block                           # BIC 1074.597
# Include the interactions in these terms:
# cardinality * category * Game_Condition * block                           # BIC 1205.45
# Include interaction between cardinality and/or category and game condition:
# cardinality + category * Game_Condition + block + (1 | gameID)           # BIC 1023.897
# cardinality + category + Game_Condition + cardinality:Game_Condition + block + (1 | gameID)    # BIC 998.1115  # didn't converge
# cardinality + category * Game_Condition + cardinality:Game_Condition + block + (1 | gameID)    # BIC 1018.259 # didn't converge

acc_model <- glmer(data=dat, outcome ~
                     cardinality + category + Game_Condition + block + (1 | gameID),
                   family = 'binomial')
acc_no_cat <- glmer(data=dat, outcome ~
                     cardinality + Game_Condition + block + (1 | gameID),
                   family = 'binomial')
acc_no_car <- glmer(data=dat, outcome ~
                     category + Game_Condition + block + (1 | gameID),
                   family = 'binomial')

anova(acc_model,acc_no_cat)
anova(acc_model,acc_no_car)

BIC(acc_model)
summary(acc_model)
```


``` {r models we settled on as the best for each DV}
summary(ink_model)
summary(str_model)
summary(dur_model)
summary(acc_model)

```
